general {
  border_size = 2
  gaps_in = 6
  gaps_out = 9
  
  col.active_border = rgba(89b4faff)
  col.inactive_border = rgba(585b70ff) 
}

decoration {
  rounding = 6
         
  active_opacity = 1
  inactive_opacity = 1
  fullscreen_opacity = 1

  dim_inactive = true
  dim_strength = 0.01
  dim_special = 0.1

  shadow {
    enabled = false
    range = 3
    render_power = 1

    color = rgba(89dcebff)
    color_inactive = rgba(6c7086ff)
  }


  blur {
    enabled = true
    size = 3
    passes = 3
    ignore_opacity = true
    new_optimizations = true
    special = true
    popups = true
  }
}

group {
  col.border_active = rgba(cdd6f4ff)

	groupbar {
		col.active = rgba(1e1e2eff)
  }
}
