#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

# General bar and defaults
echo "Using BAR_COLOR: $BAR_COLOR"
sketchybar --bar height=30 \
	color="$BAR_COLOR" \
	shadow="$SHADOW" \
	position=top \
	sticky=on \
	padding_right=1 \
	padding_left=2 \
	corner_radius="$CORNER_RADIUS" \
	y_offset=5 \
	margin=12:5:12:5 \
	blur_radius=20 \
	notch_width=200 \
	border_width=1 \
	border_color="$BLUE" \
	--default updates=when_shown \
	icon.font="$FONT:Bold:13.5" \
	icon.color="$ICON_COLOR" \
	icon.padding_left="$PADDINGS" \
	icon.padding_right="$PADDINGS" \
	label.font="$FONT:Bold:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left="$PADDINGS" \
	label.padding_right="$PADDINGS" \
	background.padding_right="$PADDINGS" \
	background.padding_left="$PADDINGS" \
	popup.background.border_width=1 \
	popup.background.corner_radius=11 \
	popup.background.border_color="$POPUP_BORDER_COLOR" \
	popup.background.color="$POPUP_BACKGROUND_COLOR" \
	popup.background.shadow.drawing="$SHADOW"

# Add event for Aerospace workspace changes
sketchybar --add event aerospace_workspace_change
sketchybar --enable-hidpi

# Add Aerospace workspaces (only 1-6)
sketchybar --add bracket spaces right_bracket
for sid in {1..6}; do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color="$BAR_COLOR" \
        background.corner_radius="$CORNER_RADIUS" \
        background.border_width="$BORDER_WIDTH" \
        background.border_color="$RED" \
        background.height=24 \
        background.drawing=off \
        background.padding_left=-2 \
        background.padding_right=-2 \
        label="$sid" \
        label.padding_left=10 \
        label.padding_right=10 \
        icon.drawing=off \
        click_script="aerospace workspace $sid" \
        script="$HOME/.config/sketchybar/plugins/aerospace.sh $sid"
    
    # Add to the workspace bracket
    sketchybar --add space.$sid to spaces
done

# Add spacer
sketchybar --add item spacer.1 left \
    --set spacer.1 background.drawing=off \
    label.drawing=off \
    icon.drawing=off \
    width=10

# Left items
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/front_app.sh"

# Center (of notch)
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

# Finalize setup
sketchybar --hotload true
sketchybar --update

echo "sketchybar configuration loaded.."
